{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c7c95e05-a877-4cba-a854-c216f2cc540e",
   "metadata": {},
   "outputs": [],
   "source": [
    "import sqlite3\n",
    "import pandas as pd\n",
    "import streamlit as st\n",
    "import plotly.express as px\n",
    "\n",
    "# ==========================================\n",
    "# CONFIGURATION & SETUP\n",
    "# ==========================================\n",
    "st.set_page_config(page_title=\"Car Rental Analytics\", layout=\"wide\")\n",
    "\n",
    "def get_data():\n",
    "    \"\"\"Fetch data from the shared SQLite database.\"\"\"\n",
    "    conn = sqlite3.connect('car_rental.db')\n",
    "    \n",
    "    # Fetch Cars Data\n",
    "    cars_df = pd.read_sql_query(\"SELECT * FROM cars\", conn)\n",
    "    \n",
    "    # Fetch Bookings Data\n",
    "    bookings_df = pd.read_sql_query(\"SELECT * FROM bookings\", conn)\n",
    "    \n",
    "    conn.close()\n",
    "    return cars_df, bookings_df\n",
    "\n",
    "# ==========================================\n",
    "# DASHBOARD LAYOUT\n",
    "# ==========================================\n",
    "try:\n",
    "    cars_df, bookings_df = get_data()\n",
    "\n",
    "    st.title(\"🚗 Car Rental System: Executive Dashboard\")\n",
    "    st.markdown(\"Real-time analytics for fleet management and revenue tracking.\")\n",
    "    \n",
    "    # --- METRICS ROW ---\n",
    "    col1, col2, col3, col4 = st.columns(4)\n",
    "    \n",
    "    total_cars = len(cars_df)\n",
    "    available_cars = len(cars_df[cars_df['available_now'] == 1])\n",
    "    rented_cars = total_cars - available_cars\n",
    "    total_revenue = bookings_df['total_fee'].sum() if not bookings_df.empty else 0\n",
    "    \n",
    "    col1.metric(\"Total Fleet Size\", f\"{total_cars} Vehicles\")\n",
    "    col2.metric(\"Available Now\", f\"{available_cars}\", delta=f\"{(available_cars/total_cars)*100:.0f}%\" if total_cars else \"0%\")\n",
    "    col3.metric(\"Currently Rented\", f\"{rented_cars}\", delta_color=\"inverse\")\n",
    "    col4.metric(\"Total Revenue\", f\"${total_revenue:,.2f}\")\n",
    "    \n",
    "    st.divider()\n",
    "\n",
    "    # --- CHARTS ROW 1 ---\n",
    "    c1, c2 = st.columns(2)\n",
    "    \n",
    "    with c1:\n",
    "        st.subheader(\"Fleet Availability Status\")\n",
    "        if not cars_df.empty:\n",
    "            # Create a Pie Chart for Availability\n",
    "            status_counts = cars_df['available_now'].map({1: 'Available', 0: 'Rented'}).value_counts().reset_index()\n",
    "            status_counts.columns = ['Status', 'Count']\n",
    "            \n",
    "            fig_pie = px.pie(status_counts, values='Count', names='Status', \n",
    "                             color='Status',\n",
    "                             color_discrete_map={'Available':'#00CC96', 'Rented':'#EF553B'},\n",
    "                             hole=0.4)\n",
    "            st.plotly_chart(fig_pie, use_container_width=True)\n",
    "        else:\n",
    "            st.info(\"No car data available.\")\n",
    "\n",
    "    with c2:\n",
    "        st.subheader(\"Revenue by Car Model\")\n",
    "        if not bookings_df.empty and not cars_df.empty:\n",
    "            # Join Bookings with Cars to get Model names\n",
    "            merged_df = pd.merge(bookings_df, cars_df, left_on='car_id', right_on='id', suffixes=('_b', '_c'))\n",
    "            revenue_by_car = merged_df.groupby('model')['total_fee'].sum().reset_index()\n",
    "            \n",
    "            fig_bar = px.bar(revenue_by_car, x='model', y='total_fee',\n",
    "                             labels={'total_fee': 'Revenue ($)', 'model': 'Car Model'},\n",
    "                             color='total_fee',\n",
    "                             color_continuous_scale='Bluyl')\n",
    "            st.plotly_chart(fig_bar, use_container_width=True)\n",
    "        else:\n",
    "            st.info(\"No booking data available yet.\")\n",
    "\n",
    "    # --- DATA TABLE ROW ---\n",
    "    st.subheader(\"Recent Booking Transactions\")\n",
    "    if not bookings_df.empty:\n",
    "        # Show the last 5 bookings\n",
    "        st.dataframe(bookings_df.tail(5).iloc[::-1], use_container_width=True)\n",
    "    else:\n",
    "        st.info(\"No transactions found in the database.\")\n",
    "\n",
    "except Exception as e:\n",
    "    st.error(f\"Error connecting to database: {e}\")\n",
    "    st.warning(\"Please ensure 'main.py' has been run at least once to generate 'car_rental.db'.\")\n",
    "\n",
    "# ==========================================\n",
    "# SIDEBAR\n",
    "# ==========================================\n",
    "with st.sidebar:\n",
    "    st.header(\"Admin Actions\")\n",
    "    st.write(\"This dashboard refreshes automatically when the database changes.\")\n",
    "    if st.button(\"Refresh Data\"):\n",
    "        st.rerun()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
